/*      */ package SCPCraft.CoroAI.entity;
/*      */ 
/*      */ import SCPCraft.CoroAI.Behaviors;
/*      */ import SCPCraft.CoroAI.PFQueue;
/*      */ import SCPCraft.CoroAI.PathEntityEx;
/*      */ import SCPCraft.CoroAI.c_IEnhAI;
/*      */ import SCPCraft.c_CoroAIUtil;
/*      */ import agi;
/*      */ import ahl;
/*      */ import anm;
/*      */ import aoh;
/*      */ import aoj;
/*      */ import bq;
/*      */ import java.util.List;
/*      */ import java.util.Random;
/*      */ import ke;
/*      */ import la;
/*      */ import lh;
/*      */ import lq;
/*      */ import md;
/*      */ import mi;
/*      */ import px;
/*      */ import qx;
/*      */ import up;
/*      */ import ur;
/*      */ import yc;
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ public class c_EnhAI
/*      */   extends c_PlayerProxy
/*      */   implements c_IEnhAI
/*      */ {
/*      */   public boolean debug = false;
/*      */   public EnumActState currentAction;
/*      */   public String name;
/*      */   public String debugInfo;
/*      */   public Random aa;
/*      */   public int jobTimeout;
/*      */   public boolean dipl_hostilePlayer = false;
/*   43 */   public EnumTeam dipl_team = EnumTeam.HOSTILES;
/*   44 */   public int dipl_spreadInfoDelay = 0;
/*      */   
/*      */   public int targX;
/*      */   
/*      */   public int targY;
/*      */   
/*      */   public int targZ;
/*      */   
/*      */   public lq followTarget;
/*      */   
/*      */   public int homeX;
/*      */   
/*      */   public int homeY;
/*      */   public int homeZ;
/*   58 */   public double maxDistanceFromHome = 96.0D;
/*      */   
/*      */   public long checkAreaDelay;
/*   61 */   public long checkRange = 16L;
/*   62 */   public int openedChest = 0;
/*      */   
/*      */   public JobManager job;
/*      */   
/*      */   public boolean occupationReady = true;
/*      */   
/*   68 */   public int dangerLevel = 0;
/*      */   
/*      */   public String oldName;
/*      */   
/*      */   public boolean facingWater = false;
/*      */   
/*      */   public boolean wasInWater = false;
/*      */   
/*      */   public float oldMoveSpeed;
/*      */   public float fleeSpeed;
/*      */   public boolean fleeing = false;
/*      */   public boolean enhanceAIEnemies = false;
/*   80 */   public int enhancedAIDelay = 100;
/*      */   
/*      */   public int aS;
/*      */   
/*      */   public lq lastFleeEnt;
/*      */   
/*      */   public boolean tryingToFlee;
/*   87 */   public float lungeFactor = 1.0F;
/*      */   private int jumpDelay;
/*      */   public double mX;
/*      */   public double mY;
/*      */   public double mZ;
/*      */   public int groupInfoDelay;
/*   93 */   public long itemLookDelay; public void initJobAndStates(EnumJob job) { initJobAndStates(job, true); } public void initJobAndStates(EnumJob job, boolean initItems) { this.job.setPrimaryJob(job); setState(EnumActState.IDLE); this.job.clearJobs(); if (job == EnumJob.HUNTER) { addJob(EnumJob.FINDFOOD); addJob(EnumJob.HUNTER); } else if (job == EnumJob.FISHERMAN) { addJob(EnumJob.FINDFOOD); addJob(EnumJob.FISHERMAN); } else if (job == EnumJob.GATHERER) { addJob(EnumJob.GATHERER); } else if (job == EnumJob.INVADER) { addJob(EnumJob.INVADER); } else if (job == EnumJob.PROTECT) { addJob(EnumJob.PROTECT); addJob(EnumJob.HUNTER); } else { addJob(EnumJob.UNEMPLOYED); }  if (initItems) { if (this.fakePlayer == null) this.fakePlayer = newFakePlayer(this.p);  setOccupationItems(); if (this.entID == -1) this.entID = this.aa.nextInt(999999999);  }  } public void swapJob(EnumJob job) { setState(EnumActState.IDLE); this.job.swapJob(job); } public void addJob(EnumJob job) { this.job.addJob(job); } public void setOccupationItems() { if (this.inventory.a[0] != null) System.out.println("Possible error - job items being added to populated inventory!");  this.job.enumToJob(this.job.priJob).setJobItems(); } public EnumActState getCurrentAction() { return this.currentAction; } public boolean isEnemy(lq entity1) { if (entity1 instanceof c_EnhAI) { if (this.dipl_team != ((c_EnhAI)entity1).dipl_team) return true;  return false; }  return c_CoroAIUtil.isEnemy(this, entity1); } public void alertHunters(lq target) { int alertRange = 128; int alertCount = 0; int alertCountMax = 5; List<lq> list = this.p.b(null, this.D.b(alertRange, (alertRange / 2), alertRange)); for (int j = 0; j < list.size(); j++) { lq entity1 = list.get(j); if (entity1 instanceof c_EnhAI && ((c_EnhAI)entity1).job.priJob == EnumJob.HUNTER) if (((c_EnhAI)entity1).job.getJobState() == EnumJobState.IDLE && ((c_EnhAI)entity1).currentAction == EnumActState.IDLE && ((c_EnhAI)entity1).a_ == null && ((c_EnhAI)entity1).job.getJobClass().sanityCheckHelp((lq)this, target)) { ((c_EnhAI)entity1).huntTarget(target); System.out.println(((c_EnhAI)entity1).name + " alerted"); alertCount++; if (alertCount > alertCountMax) return;  }   }  } public void x() { super.x(); if (this.fakePlayer != null) c_CoroAIUtil.playerToAILookup.remove(this.fakePlayer.bR);  if (PFQueue.pfDelays != null) PFQueue.pfDelays.remove(this);  if (this.job != null) { this.job.clearJobs(); this.job.jobTypes.clear(); this.job.ent = null; }  l((lq)null); } public double getDistanceXZ(double par1, double par5) { double var7 = this.t - par1; double var11 = this.v - par5; return ke.a(var7 * var7 + var11 * var11); } public void e(float f, float f1) { double d = this.t; double d1 = this.u; double d2 = this.v; super.e(f, f1); if (this.wasInWater && this.F && k() && !inWater()) this.x = 0.7D;  if (!inWater()) { this.wasInWater = false; } else { this.wasInWater = true; }  if (this.fakePlayer != null) { try { this.fakePlayer.j(this.t - d, this.u - d1, this.v - d2); } catch (NoSuchFieldError ex) {} if (this.E) if (Math.abs(this.w) * Math.abs(this.y) > 2.0E-4D) try { this.fakePlayer.j(0.0022F); } catch (NoSuchFieldError ex) {}   }  } public boolean inWater() { return this.p.a(this.D.b(-0.10000000149011612D, -0.4000000059604645D, -0.10000000149011612D), agi.h); } public void fixEnemyTargetting() { int range = 3; List<lq> list = this.p.b((lq)this, this.D.b(range, range, range)); for (int j = 0; j < list.size(); j++) { lq entity1 = list.get(j); if (entity1 instanceof mi) { lq targ = ((mi)entity1).l(); if (targ instanceof qx && ((qx)targ).bR.contains("fakePlayer")) ((mi)entity1).b(null);  }  }  } public int checkSurroundings() { fixEnemyTargetting(); if (this.checkAreaDelay < System.currentTimeMillis() && checkHealth()) { this.checkAreaDelay = System.currentTimeMillis() + 1500L + this.aa.nextInt(1000); float closest = 9999.0F; lq clEnt = null; List<lq> list = this.p.b((lq)this, this.D.b(this.checkRange, (this.checkRange / 2L), this.checkRange)); for (int j = 0; j < list.size(); j++) { lq entity1 = list.get(j); if (isEnemy(entity1)) if (((md)entity1).n((lq)this)) { float dist = d(entity1); if (dist < closest) { closest = dist; clEnt = entity1; }  }   }  if (clEnt != null) { alertHunters(clEnt); return 1; }  return 0; }  return -1; } public boolean checkHealth() { if (this.aR < aT() * 0.75D) return true;  return false; } public c_EnhAI(yc world) { super(world);
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */     
/* 1011 */     this.groupInfoDelay = 0;
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */ 
/*      */     
/* 1333 */     this.waitingForNewPath = false; this.job = new JobManager(this); this.aa = new Random(); initJobAndStates(EnumJob.FISHERMAN, false); this.homeX = -114; this.homeY = 64; this.homeZ = 908; this.homeX = 51; this.homeY = 63; this.homeZ = 311; setMoveSpeed(0.28F); this.fleeSpeed = 0.32F; this.Z = 0.9F; }
/*      */   public void updateJob() { this.job.tick(); }
/*      */   public float getMoveSpeed() { return this.bH; }
/* 1336 */   public void setMoveSpeed(float var) { this.bH = var; this.oldMoveSpeed = var; if (!this.p.I) this.ag.b(23, Integer.valueOf((int)(var * 1000.0F)));  } public void pathNav() { if (this.pathToEntity != null) { aoj curPos = this.pathToEntity.getPosition((lq)this); double var6 = (this.N * this.N); while (curPos != null && curPos.d(this.t, curPos.d, this.v) < var6 * var6) { this.pathToEntity.incrementPathIndex(); if (this.pathToEntity.isFinished()) { curPos = null; this.pathToEntity = null; continue; }  curPos = this.pathToEntity.getPosition((lq)this); }  if (curPos != null) { int var21 = ke.c(this.D.b + 0.5D); double var8 = curPos.c - this.t; double var10 = curPos.e - this.v; double var12 = curPos.d - var21; var8 = this.t - curPos.c; var10 = this.v - curPos.e; var12 = curPos.d - var21; float var14 = (float)(Math.atan2(var10, var8) * 180.0D / Math.PI) - 90.0F; float var15 = var14 - (float)this.bx; for (this.bD = this.bH; var15 < -180.0F; var15 += 360.0F); while (var15 >= 180.0F) var15 -= 360.0F;  if (var15 > 30.0F) var15 = 30.0F;  if (var15 < -30.0F) var15 = -30.0F;  if (this.a_ != null); }  if (curPos != null); }  } public void h(double par1, double par3, double par5) { this.w = par1; this.x = par3; this.y = par5; this.mX = par1; this.mY = par3; this.mZ = par5; } public void onLivingUpdate2() {} public void c() { if (this.p.I) { float speed = (this.ag.c(23) / 1000); if (this.bH != speed) setMoveSpeed(speed);  }  if (this.p.I) { if (this.ag.c(22) == 1) this.x = 0.0D;  } else if (this.E) { this.ag.b(22, Integer.valueOf(1)); } else { this.ag.b(22, Integer.valueOf(0)); }  if (c_CoroAIUtil.isServer()); float factor = this.lungeFactor; factor = this.lungeFactor; if (this.ag.c(20) == 1) { float smpFactor = 1.0F; if (c_CoroAIUtil.isServer()) smpFactor = 0.6F;  if (this.p.I); } else if (this.p.I) {  }  if (this.p.I) { if (this.ag.c(21) == 1) { if (c_CoroAIUtil.isServer()); this.swingArm = true; }  } else if (this.ag.c(21) == 1) { this.ag.b(21, Integer.valueOf(0)); }  super.c(); } public void bo() {} public void bi() { super.bi(); } public void doMovement() { if (this.aY > 0) return;  if (this.fleeing) { this.ag.b(20, Integer.valueOf(1)); } else if (this.a_ != null && isSolidPath(this.a_)) { this.job.getJobClass().onCloseCombatTick(); } else if (!az().f()) { this.ag.b(20, Integer.valueOf(1)); aoj vec = az().d().a((lq)this); } else { this.ag.b(20, Integer.valueOf(0)); }  if (this.bD <= 0.0F) this.ag.b(20, Integer.valueOf(0));  if (H() && this.jumpDelay == 0) { if (this.a_ != null); this.x += 0.03D; if (az().d() != null) { ahl pEnt = az().d(); int index = pEnt.e() + 1; if (index < 0) index = 0;  if (index > pEnt.d()) index = pEnt.d() - 1;  aoj var1 = null; try { var1 = pEnt.a((lq)this, pEnt.e()); } catch (Exception ex) { var1 = pEnt.a((lq)this, pEnt.d() - 1); }  if (var1 != null) { ax().a(var1.c, var1.d, var1.e, 0.53F); double dist = f(var1.c, var1.d, var1.e); if (dist < 8.0D); if (dist < 2.0D) az().d().a();  }  }  }  if (!this.E || this.jumpDelay == 0); this.T = this.t; this.U = this.u; this.V = this.v; } public boolean isBreaking() { return false; } protected void a() { super.a(); this.ag.a(20, Integer.valueOf(0)); this.ag.a(21, Integer.valueOf(0)); this.ag.a(22, Integer.valueOf(0)); this.ag.a(23, Integer.valueOf(0)); } public void bH() { super.bH(); } public boolean canSeeBlock(int x, int y, int z) { aoh mop = this.p.a(aoj.a(this.t, this.u + e(), this.v), aoj.a(x, y, z)); if (mop == null) return true;  if (mop.b == x && mop.c == y && mop.d == z) return true;  return false; } public void checkPathfindLock() { if (this.waitingForNewPath)
/* 1337 */     { az().a(PFQueue.convertToPathEntity(this.pathToEntity), getMoveSpeed());
/* 1338 */       this.waitingForNewPath = false; }  } public void updateAI() { if (this.L) return;  doMovement(); try { if (this.a_ == this.fakePlayer) this.a_ = null;  } catch (Error ex) {} if (this.a_ != null && this.a_.S()) { float var2 = this.a_.d((lq)this); if (n(this.a_)) a(this.a_, var2);  } else { this.a_ = null; }  double var12 = 1.0D; if (var12 > 0.0D); if (!this.F || k()); if (this.pfTimeout > 0) this.pfTimeout--;  if (this.groupInfoDelay > 0) this.groupInfoDelay--;  if (this.dipl_spreadInfoDelay > 0) this.dipl_spreadInfoDelay--;  if (this.jumpDelay > 0) this.jumpDelay--;  if (this.enhancedAIDelay-- <= 0) { this.enhancedAIDelay = 100 + this.aa.nextInt(50); if (this.enhanceAIEnemies) Behaviors.enhanceMonsterAI((md)this);  }  if (this.openedChest > 0) { this.openedChest--; if (this.openedChest == 0) closeHomeChest();  }  if (!H()) { this.wasInWater = false; int yyStart = (int)this.u; for (int yy = 1; yy > -20; yy--) { int id = 0; if (isBlockWater(id)) { this.facingWater = true; } else if (id != 0) { break; }  }  } else { this.wasInWater = true; this.facingWater = false; }  if (this.homeX == 0) getGroupInfo(EnumInfo.HOME_COORD);  if (this.dipl_spreadInfoDelay == 0) { this.dipl_spreadInfoDelay = 20 + this.aa.nextInt(10); getGroupInfo(EnumInfo.DIPL_WARN); }  if (this.oldName == null) this.oldName = this.name;  int pfNodes = 0; if (this.pathToEntity != null && this.pathToEntity.points != null) pfNodes = this.pathToEntity.points.length;  this.debugInfo = this.oldName + ": " + this.aR + "|" + getFoodLevel() + " | " + this.job.priJob + " -> " + this.job.getJobState() + "|" + this.currentAction + "|" + pfNodes + "|"; if (!this.debug) this.name = this.oldName;  this.dangerLevel = 0; if (checkSurroundings() == 1) this.dangerLevel = 1;  if (checkHealth()) this.dangerLevel = 2;  this.job.getJobClass().checkHunger(); this.fleeing = false; if (this.dangerLevel == 0) { updateJob(); this.bH = this.oldMoveSpeed; } else if (this.dangerLevel == 1) { updateJob(); this.bH = this.oldMoveSpeed; } else if (this.dangerLevel == 2) { if (!this.job.getJobClass().avoid(true)) { this.fleeing = false; updateJob(); this.bH = this.oldMoveSpeed; } else { this.fleeing = true; this.job.getJobClass().onLowHealth(); this.bH = this.fleeSpeed; }  }  if (this.currentAction == EnumActState.IDLE && this.job.getJobState() == EnumJobState.IDLE) { this.job.getJobClass().onIdleTick(); if (this.pathToEntity != null && this.pathToEntity.points != null && this.pathToEntity.points.length > 0) { (this.job.getJobClass()).walkingTimeout--; if ((this.job.getJobClass()).walkingTimeout <= 0); }  } else if (this.currentAction == EnumActState.FIGHTING) { actFight(); } else if (this.currentAction == EnumActState.WALKING) { actWalk(); } else if (this.currentAction == EnumActState.FOLLOWING) { actFollow(); }  } public void setState(EnumActState eka) { this.currentAction = eka; } public void walkTo(lq var1, int x, int y, int z, float var2, int timeout) { walkTo(var1, x, y, z, var2, timeout, 0); } public void walkTo(lq var1, int x, int y, int z, float var2, int timeout, int priority) { PFQueue.getPath((lq)this, x, y, z, this.maxPFRange, priority); setState(EnumActState.WALKING); (this.job.getJobClass()).walkingTimeout = timeout; this.targX = x; this.targY = y; this.targZ = z; } public void getGroupInfo(EnumInfo eki) { if (this.groupInfoDelay > 0) return;  this.groupInfoDelay = 10; if (eki == EnumInfo.HOME_COORD) { c_EnhAI koa = (c_EnhAI)getEnt(false, true); if (koa != null) { this.homeX = koa.homeX; this.homeY = koa.homeY; this.homeZ = koa.homeZ; }  } else if (eki == EnumInfo.DIPL_WARN) { int range = 64; List<lq> list = this.p.b((lq)this, this.D.b(range, (range / 2), range)); for (int j = 0; j < list.size(); j++) { lq entity1 = list.get(j); if (entity1 instanceof c_EnhAI && n(entity1) && ((c_EnhAI)entity1).dipl_team == this.dipl_team) ((c_EnhAI)entity1).dipl_hostilePlayer = this.dipl_hostilePlayer;  }  }  } public lq getEnt(boolean ally, boolean koa) { int range = 64; List<lq> list = this.p.b((lq)this, this.D.b(range, (range / 2), range)); for (int j = 0; j < list.size(); j++) { lq entity1 = list.get(j); if (koa) { if (entity1 instanceof c_EnhAI) return entity1;  } else if ((!ally && isEnemy(entity1)) || (ally && !isEnemy(entity1))) { return entity1; }  }  return null; } public boolean isIdle() { if (this.job.getJobState() == EnumJobState.IDLE && this.currentAction == EnumActState.IDLE) return true;  return false; } public boolean isIdleWalking() { if (this.job.getJobState() == EnumJobState.IDLE && (this.currentAction == EnumActState.IDLE || this.currentAction == EnumActState.WALKING)) return true;  return false; } public boolean canTrade() { if (this.dipl_hostilePlayer) return false;  if (this.job.getJobState() == EnumJobState.IDLE && (this.currentAction == EnumActState.IDLE || this.currentAction == EnumActState.WALKING)) return true;  if (this.job.priJob == EnumJob.FISHERMAN && this.job.getJobState() == EnumJobState.W2) return true;  return false; }
/*      */   public int getItemCount(int id) { int count = 0; for (int j = 0; j < this.inventory.a.length; j++) { if (this.inventory.a[j] != null && (this.inventory.a[j]).c == id) count += (this.inventory.a[j]).a;  }  return count; }
/*      */   public void openHomeChest() { if (isChest(this.p.a(this.homeX, this.homeY, this.homeZ))) { anm chest = (anm)this.p.q(this.homeX, this.homeY, this.homeZ); if (chest != null) { this.openedChest = 10; chest.l_(); }  }  }
/*      */   public void closeHomeChest() { if (isChest(this.p.a(this.homeX, this.homeY, this.homeZ))) { anm chest = (anm)this.p.q(this.homeX, this.homeY, this.homeZ); if (chest != null) { this.openedChest = 0; chest.f(); }  }  }
/*      */   public boolean isChest(int id) { return c_CoroAIUtil.isChest(id); }
/*      */   public void takeItems(int x, int y, int z, int id, boolean food) { if (isChest(this.p.a(x, y - 1, z))) y--;  boolean transferred = false; if (isChest(this.p.a(x, y, z))) { anm chest = (anm)this.p.q(x, y, z); if (chest != null) { openHomeChest(); this.job.getPrimaryJobClass().transferItems((la)chest, (la)this.inventory, id, 1, food); }  }  }
/*      */   public void setInventorySlotContents(anm chest, int i, ur itemstack) { ur is = chest.a(i); }
/* 1345 */   public synchronized void setPathExToEntity(PathEntityEx pathentity) { this.pathToEntity = pathentity;
/* 1346 */     this.waitingForNewPath = true; } public void huntTarget(lq ent, int pri) { PFQueue.getPath((lq)this, ent, this.maxPFRange, pri); this.a_ = ent; setState(EnumActState.FIGHTING); } public void huntTarget(lq ent) { huntTarget(ent, 0); } public void actFight() { if (this.a_ == null || this.a_.L) { this.a_ = null; setState(EnumActState.IDLE); }  } public void actWalk() { (this.job.getJobClass()).walkingTimeout--; if (f(this.targX, this.targY, this.targZ) < 2.0D || az().d() == null || az().d().b()) { setPathToEntity((PathEntityEx)null); az().g(); setState(EnumActState.IDLE); } else if ((this.job.getJobClass()).walkingTimeout <= 0) { setPathToEntity((PathEntityEx)null); az().g(); setState(EnumActState.IDLE); }  } public void actFollow() { md entityplayer = null; this.followTarget = (lq)entityplayer; if (this.followTarget != null) if (entityplayer != null && this.aa.nextInt(30) < 3) { float f = entityplayer.d((lq)this); if (f > 10.0F) getPathOrWalkableBlock((lq)entityplayer, f);  }   } public void lookForItems() { this.itemSearchRange = 10; if (this.itemLookDelay < System.currentTimeMillis()) { this.itemLookDelay = System.currentTimeMillis() + 500L; List<lq> var3 = this.p.b((lq)this, this.D.b(this.itemSearchRange * 1.0D, this.itemSearchRange * 1.0D, this.itemSearchRange * 1.0D)); if (var3 != null) for (int var4 = 0; var4 < var3.size(); var4++) { lq var5 = var3.get(var4); if (!var5.L && var5 instanceof px) { px ent = (px)var5; if (this.wantedItems.contains(Integer.valueOf((ent.d().b()).cj)) && n(var5)) if (!var5.a(agi.h)) targetItem(var5);   } else if (var5 instanceof lz && n(var5) && !var5.a(agi.h)) { targetItem(var5); }  }   }  } public void targetItem(lq item) { PFQueue.getPath((lq)this, item, this.itemSearchRange + 2.0F); if (k()) setState(EnumActState.WALKING);  } public void a(bq var1) { super.a(var1); try { this.entID = var1.e("entID"); this.targX = var1.e("targX"); this.targY = var1.e("targY"); this.targZ = var1.e("targZ"); this.homeX = var1.e("homeX"); this.homeY = var1.e("homeY"); this.homeZ = var1.e("homeZ"); initJobAndStates(EnumJob.get(var1.e("primaryOccupation")), false); this.currentAction = EnumActState.get(var1.e("currentAction")); (this.job.getJobClass()).tradeTimeout = var1.e("tradeTimeout"); this.name = var1.i("name"); this.dipl_hostilePlayer = var1.n("dipl_hostilePlayer"); this.homeZ = var1.e("homeZ"); } catch (Exception ex) { ex.printStackTrace(); }  } public void b(bq var1) { super.b(var1); try { var1.a("entID", this.entID); var1.a("targX", this.targX); var1.a("targY", this.targY); var1.a("targZ", this.targZ); var1.a("homeX", this.homeX); var1.a("homeY", this.homeY); var1.a("homeZ", this.homeZ); var1.a("primaryOccupation", this.job.priJob.ordinal()); var1.a("tradeTimeout", (this.job.getJobClass()).tradeTimeout); if (this.oldName != null && this.oldName != "") this.name = this.oldName;  if (this.name != null) var1.a("name", this.name);  var1.a("dipl_hostilePlayer", this.dipl_hostilePlayer); var1.a("dipl_team", this.dipl_team.ordinal()); if (this.currentAction != null) var1.a("currentAction", this.currentAction.ordinal());  } catch (Exception ex) { ex.printStackTrace(); }  }
/*      */   public void noMoveTriggerCallback() { if (this.currentAction == EnumActState.IDLE && this.job.getJobState() == EnumJobState.IDLE) setEntityToAttack((lq)null);  az().a(null, 0.0F); setPathExToEntity((PathEntityEx)null); }
/*      */   public boolean a(lh damagesource, int i) { if (this.job != null && this.job.getJobClass() != null) this.job.getJobClass().hitHook(damagesource, i);  return super.a(damagesource, i); }
/*      */   protected String aY() { return null; }
/*      */   protected static final ur defaultHeldItem = new ur(up.aR, 1); public boolean waitingForNewPath;
/*      */   public boolean canUseLadders() { return false; }
/* 1352 */   public int overrideBlockPathOffset(c_IEnhAI ent, int id, int meta, int x, int y, int z) { return -66; }
/*      */ 
/*      */ }


/* Location:              /home/luigi/Documents/JAR.jar!/SCPCraft/CoroAI/entity/c_EnhAI.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */